### ISSUE TITLE
cm-statement node does not support parameters from config node

### ISSUE THREAD

**Issue by namtab00** [peterprib/node-red-contrib-connectionmanager#2]
Setting a parameter from the flow config scope
![image](https://user-images.githubusercontent.com/995900/83809641-1df45800-a6b7-11ea-8ad2-0942869e890f.png)

yields:

```
ReferenceError: flow is not defined
    at cmStatementNode.eval [as mappingCompiled] (eval at cmStatementNode (/data/node_modules/node-red-contrib-connectionmanager/connectionManager/cm-statement.js:128:27), <anonymous>:1:61)
    at cmStatementNode._inputCallback (/data/node_modules/node-red-contrib-connectionmanager/connectionManager/cm-statement.js:163:76)
    at cmStatementNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by peterprib** [comment]
These can be passed in msg.  In theory you can get at it via node._flow.   Will treat this as enhancement request and include env and global at same time.

**Comment by peterprib** [comment]
have deployed v0.0.2 which should give access flow.get("aproperty"), global.get("aproperty") and env.get("aproperty")
